Fixed broken example in readme
The example code in the readme didn't run:

	/Users/vicwid/code/swxl/node_modules/modbus-tcp/lib/Server/Server.js:40
			stream.pipe(reader);
			       ^
	TypeError: Cannot call method 'pipe' of undefined
	    at Server.pipe (/Users/vicwid/code/swxl/node_modules/modbus-tcp/lib/Server/Server.js:40:10)
	    at Object.<anonymous> (/Users/vicwid/code/swxl/modbustest.js:6:20)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:901:3

I modified the piping to match the code in the tests.

I also added a console.log() to the response callback, so the code outputs something.